In [0]:
import pandas as pd
import numpy as np

In [0]:
df=pd.read_csv('merge_from_ofoct.txt',names=["cita_nac","ced_padre", "ced_madre","cod_hosp","hora_nac","fecha_nac","sexo","relleno","nac_hijo","defunc","pais_padre","pais_madre","advert","ape1","ape2","nombre","nombre_padre","nombre_madre","lugar_nac","tipo_mov","fecha_marg","hora_marg","fecha_natura","indic_ext","prov_cant_madre","fec_aplic"],encoding="latin-1")
df_ene = pd.read_csv('merge_from_ofoct.txt',names=["dato"],encoding="latin-1")

In [0]:
df_ene.info

<bound method DataFrame.info of                                                      dato
0       4032806201241154008242072003450000000201807082...
1       4032806501297019109097019205030000000201807091...
2       5053745409085041206705041207810000000201807071...
3       4032806501304017009584019201910000000201807091...
4       1162147209446010008722042904420000000199510162...
5       4023226205240000000004015104950000000199609032...
6       1230731606320000000000000000000000000201806102...
7       1230732006401123200191146006800000000201806082...
8       1230732106411169008261170804020000000201806082...
9       1230732406481147404501146501650000000201806092...
10      1230732606510000000000000000000000000201806061...
11      1230733306660000000000000000000000000201806071...
12      1230735207031063103230000000000000000201806022...
13      1230725105011140205711121802020000000201806241...
14      7035017603520000000000000000000000000200912021...
15      1207530005997011405377015501080000000200912162...
16      5051541508301158503351160407630000000201409141...
17      7038526605327011405377015501080000000201408131...
18      3062125405073033400801121202750000000201409111...
19      1224129605921096003099010304320000000201511041...
20      8011125905170000000000000000000000000200006291...
21      1223830606111154208391174208120000000201509192...
22      6055316203230000000006054506680000000201504202...
23      7038926205240000000000000000000000000201502121...
24      1224730706141174604901183804750000000201601112...
25      1224732606521122300921100108100000000201601201...
26      3063037807561124701933047404950000000201601251...
27      2102227105422055309342052606230000000201703072...
28      1226615903181136002731127708540000000201610171...
29      4026123704739007608090000000000000000200309112...
...                                                   ...
128723  1229026705331142105941165200600000000201709191...
128724  2103330906180000000000000000000000000201712071...
128725  5053430906181165309785044100190000000201711291...
128726  6056905801156040605061160509350000000201711251...
128727  2103417503494020802782074007580000000201712271...
128728  1229624104811148408581151207870000000201801092...
128729  3064313502703046208363045407330000000201802062...
128730  6056947109426037101646039501010000000201712181...
128731  1229628805761166006771168909040000000201801152...
128732  1229635907181123908571149009140000000201712272...
128733  1229539607921152509051170000280000000201712181...
128734  1229709401881140508801161909830000000201712311...
128735  1197624504900000000000000000000000000200609032...
128736  6056848109621127008111148207420000000201711082...
128737  2032014802960000000000000000000000000195609281...
128738  5053332606515035206148010703740000000201709211...
128739  5053332606525035206148010703740000000201709211...
128740  5053418103615032702135037709340000000201711142...
128741  7040911102227016102467019305260000000201709301...
128742  1228409601911134905071105507700000000201706222...
128743  2102204900980000000001139109280000000201701301...
128744  1228400700131144207201148207260000000201707061...
128745  3048641708330000000003032606560000000199505222...
128746  1227820004001137403411160009920000000201703231...
128747  1228114602911172103121175304320000000201705191...
128748  1228014402880000000007012607730000000201705151...
128749  3063918703731133108011107102640000000201705292...
128750  3063903600711167107981162608570000000201705142...
128751  1227748709740000000001156104490000000201704162...
128752  1227910102011087204260000000000000000201704021...

[128753 rows x 1 columns]>

In [0]:
df["cita_nac"]=(df_ene["dato"].apply(lambda x: x[:12]))
df["ced_padre"]=(df_ene["dato"].apply(lambda x: x[12:21]))
df["ced_madre"]=(df_ene["dato"].apply(lambda x: x[21:30]))
df["cod_hosp"]=(df_ene["dato"].apply(lambda x: x[30:33]))
df["hora_nac"]=(df_ene["dato"].apply(lambda x: x[33:37]))
df["fecha_nac"]=(df_ene["dato"].apply(lambda x: x[37:45]))
df["sexo"]=(df_ene["dato"].apply(lambda x: x[45:46]))
df["relleno"]=(df_ene["dato"].apply(lambda x: x[46:48]))
df["nac_hijo"]=(df_ene["dato"].apply(lambda x: x[48:49]))
df["defunc"]=(df_ene["dato"].apply(lambda x: x[49:50]))
df["pais_padre"]=(df_ene["dato"].apply(lambda x: x[50:53]))
df["pais_madre"]=(df_ene["dato"].apply(lambda x: x[53:56]))
df["advert"]=(df_ene["dato"].apply(lambda x: x[56:57]))
df["ape1"]=(df_ene["dato"].apply(lambda x: x[57:70]))
df["ape2"]=(df_ene["dato"].apply(lambda x: x[70:83]))
df["nombre"]=(df_ene["dato"].apply(lambda x: x[83:113]))
df["nombre_padre"]=(df_ene["dato"].apply(lambda x: x[113:142]))
df["nombre_madre"]=(df_ene["dato"].apply(lambda x: x[142:171]))
df["lugar_nac"]=(df_ene["dato"].apply(lambda x: x[171:200]))
df["tipo_mov"]=(df_ene["dato"].apply(lambda x: x[200:201]))
df["fecha_marg"]=(df_ene["dato"].apply(lambda x: x[201:209]))
df["hora_marg"]=(df_ene["dato"].apply(lambda x: x[209:215]))
df["fecha_natura"]=(df_ene["dato"].apply(lambda x: x[215:223]))
df["indic_ext"]=(df_ene["dato"].apply(lambda x: x[223:224]))
df["prov_cant_madre"]=(df_ene["dato"].apply(lambda x: x[224:227]))
df["fec_aplic"]=(df_ene["dato"].apply(lambda x: x[227:235]))


#, "","","","","","","","","","","","","","","","","","","","","","",""

In [0]:
df.head(10)

       cita_nac  ced_padre  ced_madre  ... indic_ext prov_cant_madre fec_aplic
0  403280620124  115400824  207200345  ...         0             401  20180709
1  403280650129  701910909  701920503  ...         0             401  20180709
2  505374540908  504120670  504120781  ...         0             501  20180709
3  403280650130  401700958  401920191  ...         0             401  20180709
4  116214720944  601000872  204290442  ...         0             000  20180709
5  402322620524  000000000  401510495  ...         0             000  20180709
6  123073160632  000000000  000000000  ...         0             101  20180709
7  123073200640  112320019  114600680  ...         0             101  20180709
8  123073210641  116900826  117080402  ...         0             101  20180709
9  123073240648  114740450  114650165  ...         0             101  20180709

[10 rows x 26 columns]

In [0]:
df.info

<bound method DataFrame.info of             cita_nac  ced_padre  ced_madre  ... indic_ext prov_cant_madre fec_aplic
0       403280620124  115400824  207200345  ...         0             401  20180709
1       403280650129  701910909  701920503  ...         0             401  20180709
2       505374540908  504120670  504120781  ...         0             501  20180709
3       403280650130  401700958  401920191  ...         0             401  20180709
4       116214720944  601000872  204290442  ...         0             000  20180709
5       402322620524  000000000  401510495  ...         0             000  20180709
6       123073160632  000000000  000000000  ...         0             101  20180709
7       123073200640  112320019  114600680  ...         0             101  20180709
8       123073210641  116900826  117080402  ...         0             101  20180709
9       123073240648  114740450  114650165  ...         0             101  20180709
10      123073260651  000000000  000000000  ...         0             101  20180709
11      123073330666  000000000  000000000  ...         0             101  20180709
12      123073520703  106310323  000000000  ...         0             101  20180709
13      123072510501  114020571  112180202  ...         0             101  20180709
14      703501760352  000000000  000000000  ...         0             702  20180709
15      120753000599  701140537  701550108  ...         0             101  20180709
16      505154150830  115850335  116040763  ...         0             501  20180709
17      703852660532  701140537  701550108  ...         0             701  20180709
18      306212540507  303340080  112120275  ...         0             301  20180709
19      122412960592  109600309  901030432  ...         0             101  20180709
20      801112590517  000000000  000000000  ...         0             000  20180709
21      122383060611  115420839  117420812  ...         0             101  20180709
22      605531620323  000000000  605450668  ...         0             611  20180709
23      703892620524  000000000  000000000  ...         0             701  20180709
24      122473070614  117460490  118380475  ...         0             101  20180709
25      122473260652  112230092  110010810  ...         0             101  20180709
26      306303780756  112470193  304740495  ...         0             301  20180709
27      210222710542  205530934  205260623  ...         0             201  20180709
28      122661590318  113600273  112770854  ...         0             101  20180709
29      402612370473  900760809  000000000  ...         0             401  20180709
...              ...        ...        ...  ...       ...             ...       ...
128723  122902670533  114210594  116520060  ...         0             103  20180731
128724  210333090618  000000000  000000000  ...         0             210  20180731
128725  505343090618  116530978  504410019  ...         0             502  20180731
128726  605690580115  604060506  116050935  ...         0             601  20180731
128727  210341750349  402080278  207400758  ...         0             201  20180731
128728  122962410481  114840858  115120787  ...         0             119  20180731
128729  306431350270  304620836  304540733  ...         0             301  20180731
128730  605694710942  603710164  603950101  ...         0             608  20180731
128731  122962880576  116600677  116890904  ...         0             101  20180731
128732  122963590718  112390857  114900914  ...         0             101  20180731
128733  122953960792  115250905  117000028  ...         0             119  20180731
128734  122970940188  114050880  116190983  ...         0             101  20180731
128735  119762450490  000000000  000000000  ...         0             101  20180731
128736  605684810962  112700811  114820742  ...         0             601  20180731
128737  203201480296  000000000  000000000  ...         0             000  20180731
128738  505333260651  503520614  801070374  ...         0             501  20180731
128739  505333260652  503520614  801070374  ...         0             501  20180731
128740  505341810361  503270213  503770934  ...         0             501  20180731
128741  704091110222  701610246  701930526  ...         0             702  20180731
128742  122840960191  113490507  110550770  ...         0             101  20180731
128743  210220490098  000000000  113910928  ...         0             210  20180731
128744  122840070013  114420720  114820726  ...         0             101  20180731
128745  304864170833  000000000  303260656  ...         0             301  20180731
128746  122782000400  113740341  116000992  ...         0             103  20180731
128747  122811460291  117210312  117530432  ...         0             101  20180731
128748  122801440288  000000000  701260773  ...         0             101  20180731
128749  306391870373  113310801  110710264  ...         0             301  20180731
128750  306390360071  116710798  116260857  ...         0             301  20180731
128751  122774870974  000000000  115610449  ...         0             101  20180731
128752  122791010201  108720426  000000000  ...         0             101  20180731

[128753 rows x 26 columns]>

In [0]:
df.shape

(128753, 26)

In [0]:
df.to_csv("2018.csv", index=False)